sudo: required
language: node_js
node_js:
 - "8"

addons:
  apt:
    packages:
      - xvfb

before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

cache:
  yarn: true

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1600x1156x72 > /dev/null 2>&1 &

script:
  - yarn install
  - yarn lint
  - yarn build
  - yarn test
  - find src -type f -name "*diff.png" -exec openssl  base64 -in {} \;
  - yarn dist